project:
  type: book

book:
  title: "Health Data Literacy"
  author: "Chandan Kaur"
  chapters:
    - index.qmd
    - 01-Counts-vs-Rates.qmd
    - 02-Mean-vs-Median.qmd
    - 03-Correlation-vs-Causation.qmd
    - 04-Variation-&-Distributions.qmd
    - 05-Standardisation-&-Fair-Comparison.qmd
    - 06-How-to-Read-a-Dashboard.qmd
    - 07-Thinking-About-Evidence-&-Evaluation.qmd
    - 08-Evaluating-Methods-in-Practice.qmd
    - Project.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    html-math-method: mathjax
    include-in-header: include.html
