project:
  type: book

book:
  title: "Health Data Literacy"
  author: "Chandan Kaur"
  chapters:
    - index.qmd
    - modules/01-Counts-vs-Rates.qmd
    - modules/02-Mean-vs-Median.qmd
    - modules/03-Correlation-vs-Causation.qmd
    - modules/04-Variation-&-Distributions.qmd
    - modules/05-Standardisation-&-Fair-Comparison.qmd
    - modules/06-How-to-Read-a-Dashboard.qmd
    - modules/07-Thinking-About-Evidence-&-Evaluation.qmd
    - modules/08-Evaluating-Methods-in-Practice.qmd
    - modules/09-Risk-Probability-Uncertainty.qmd
    - Project.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    html-math-method: mathjax
    include-in-header: include.html
